# -*- coding: utf-8 -*-
"""Broadcasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1feWRYknbOAUlXcY88adVB7D2D9b2JJCC
"""

import numpy as np

A = np.array([[56.0,0.0, 4.4, 68.0],
            [1.2,104.0,52.0,8.0],
            [1.8,135.0,99.0,0.9]])

print(A)

cal = A.sum(axis = 0)

print(cal)

percentage = 100*A/cal.reshape(1,4)
print(percentage)

