# -*- coding: utf-8 -*-
"""EWMA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CLNOtr_vyVVPCClqZBjRI8Av2yJwnRTl
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Sample data: daily closing prices
data = [10, 20, 30, 40, 50, 40, 30, 20, 10, 30, 50, 70, 90]

# Convert to Pandas Series
data_series = pd.Series(data)

# Calculate EWMA with different alpha values
ewma_short_term = data_series.ewm(alpha=0.8).mean()
ewma_long_term = data_series.ewm(alpha=0.2).mean()

# Plotting
plt.figure(figsize=(12, 6))
plt.plot(data_series, label='Original Data', marker='o')
plt.plot(ewma_short_term, label='EWMA (alpha=0.8) - Short-Term')
plt.plot(ewma_long_term, label='EWMA (alpha=0.2) - Long-Term')
plt.legend()
plt.xlabel('Time')
plt.ylabel('Price')
plt.title('Exponentially Weighted Moving Averages for Short-Term and Long-Term Trading')
plt.show()

