# -*- coding: utf-8 -*-
"""Forward_Prop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fpxzn--qBqAqoDvTh7ezbVXSUI65wwmV
"""

import numpy as np

input_data = np.array([1, 2])

weights = {'node0': np.array([1, 1]), 'node1': np.array([-1, 1]), 'output': np.array([2, -1])}

# Top node of hidden layer
node_0_value = (input_data * weights['node0']).sum()

# Bottom node of hidden layer
node_1_value = (input_data * weights['node1']).sum()

hidden_layer_results = np.array([node_0_value, node_1_value])
print(hidden_layer_results)
# Output: [3 1]

output = (hidden_layer_results * weights['output']).sum()
print(output)
# Output: 5

