# -*- coding: utf-8 -*-
"""Numpy_Vectors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16R1McbYr9UOytbIpnAA0dw6xfv9Nq6rr
"""

import numpy as np

a = np.random.randn(5)

print(a)

print(a.shape)

print(a.T)

print(np.dot(a,a.T))

a = np.random.randn(5,1)
print(a)

print(a.shape)

print(a.T)

print(np.dot(a,a.T))

